
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IP = 13;
  public static final int DATE = 11;
  public static final int TIME = 5;
  public static final int V = 8;
  public static final int SERVER = 4;
  public static final int DATA = 6;
  public static final int INIZIO = 2;
  public static final int PV = 7;
  public static final int EOF = 0;
  public static final int NUMERO = 14;
  public static final int PP = 9;
  public static final int error = 1;
  public static final int KBS = 3;
  public static final int ORA = 10;
  public static final int CANZONE = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INIZIO",
  "KBS",
  "SERVER",
  "TIME",
  "DATA",
  "PV",
  "V",
  "PP",
  "ORA",
  "DATE",
  "CANZONE",
  "IP",
  "NUMERO"
  };
}

